### ISSUE TITLE
Estimation using my own facial image data.

### ISSUE THREAD

**Issue by tawichi** [kdhht2334/ELIM_FER#4]
Thanks for the amazing work!

For my own research, I would like to estimate valence-arousal using my own facial image data.
Which script should I use for this?
I thought [this part](https://github.com/kdhht2334/ELIM_FER/blob/main/demo/main.py#L166-L184) was estimating valence and arousal, but I am not sure what "def hand_detection()" is doing.

Can you provide a script to estimate valence-arousal from a single image using pre-trained weights?

**Comment by kdhht2334** [comment]
Hi!

`hand_detection` is a signal used to recognize non-verbal expressions other than facial expressions.

For now, we only use facial expressions, so this part doesn't have much meaning (you can delete it).

**Comment by kdhht2334** [comment]
Also, you can see below.
  - https://github.com/kdhht2334/ELIM_FER/blob/main/preprocessing.py

I just uploaded my personal version for data preprocessing.
