### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tawichi** [kdhht2334/ELIM_FER#5]
Hi.
Thank you for the amazing work!
Could you clarify the license for this code? I would like to utilize this valence-arousal estimation model in my research.

**Comment by kdhht2334** [comment]
MIT License!

I just make sure the license of this repo.

See below
  - https://github.com/kdhht2334/ELIM_FER/blob/main/LICENSE

**Comment by tawichi** [comment]
Thank you for your reply!
