### ISSUE TITLE
offset of valence and arousal 

### ISSUE THREAD

**Issue by tawichi** [kdhht2334/ELIM_FER#6]
Hi.

Thank you for the amazing work.

I have a question about offsets in scripts. [In your code](https://github.com/kdhht2334/ELIM_FER/blob/main/demo/main.py#L163), you set offset values for valence and arousal. Can you tell me why this is necessary and how you determined these values?

**Comment by kdhht2334** [comment]
Oh, you found it.

In fact, the model was trained from data consisting mainly of Western.

However, our demo environment was primarily Asian.
   - __Interracial bias occurred__.

So, for convenience, we adjusted the Asian result by giving an offset.

If you wish, you can override this offset.

**Comment by tawichi** [comment]
Thank you for your response!
I got it.
